apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-new
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    sentry.io/project-slug: YOUR_PROJECT_SLUG
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
