apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-new
  description: An example of a Backstage application.
  Tags: A tag test for bagstage.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    jenkins.io/job-full-name: 'audio_nextjs/staging'
spec:
  type: service
  owner: john@example.com
  lifecycle: experimental